GOVERNANCE.md
OWNERS.md
README.md

This repository has not had it's README
updated since aep.dev was forked.

chore: update readme and others

---

aep/general/0001/aep.yaml
aep/general/0002/aep.yaml
aep/general/0126/aep.yaml
aep/general/0131/aep.yaml
aep/general/0132/aep.yaml
aep/general/0136/aep.yaml
aep/general/0141/aep.md
aep/general/0141/aep.yaml
aep/general/0142/aep.yaml
aep/general/0144/aep.yaml
aep/general/0145/aep.yaml
aep/general/0151/aep.yaml
aep/general/0151/lro.oas.yaml
aep/general/0154/aep.yaml
aep/general/0158/aep.yaml
aep/general/0164/aep.yaml
aep/general/0210/aep.yaml
aep/general/0211/aep.yaml
aep/general/scope.yaml
requirements.txt

As site-generator now supports slugs and categories, adding them retroactively to all AEPs.

fix: adding slugs and categories

---

aep/general/0122/aep.md
aep/general/0122/aep.yaml

This is an adaptation of Roblox's AIP-122, which is an adaptation of Google's AIP-122.
This primary difference from Google's AIP-122 is the change from "name" to "path" for the key concept defined by the AEP.
Some notes on this PR:
* This PR currently has protobuf-only guidance.  If the content is generally acceptable to the working group, I'm happy to add the relevant OAS tabs.
* The proposed new numbering scheme is ignored, because there are existing AEPs that don't use it.  If and when we change the numbering scheme, a separate PR will be required anyway.
* The PR uses apis.example.com/<api> (Roblox pattern) rather than "<api>.exampleapis.com" (Google pattern).  No strong feeling about this either way.
Addresses #55.

Adopt AEP-122: Resource paths

---

aep/general/0003/aep.md
aep/general/0003/aep.yaml
aep/general/0126/aep.yaml
aep/general/0151/aep.yaml
aep/general/0211/aep.yaml
aep/general/scope.yaml

As a precursor to additional AEPs (e.g. resource types),
adding a glossary to ensure common terminology across
the AEP document.

feat(AEP-3): add AEP for glossary

---

aep/general/0155/aep.md
aep/general/0155/aep.yaml

This is a pretty straightforward adoption of Google's AIP-155.  The only substantial change is the renaming of the field from `request_id` to `idempotency_key`.  See the new subsection of the Rationale section for an explanation.

Adopt AEP-155: Idempotency

---

aep/general/0003/aep.md
aep/general/0004/aep.md
aep/general/0004/aep.yaml
common-components/json_schema/x-aep-resource.yaml

Porting the resource types AEP from google.aip.dev.
Specific changes:
- Rename from resource name to resource path, to be consistent with
aeps.
- Instead of introducing new terminology within the AEP, updating
/glossary instead.

feat(resource-types): add resource-types

---

CONTRIBUTING.md

To help with onboarding and migration of more AEPs, adding a contributors guide.

chore: adding contributors guides

---

MAINTAINERS.md

Guessing a bulk edit removed the reference to the original aip effort.

Typo fix and restore the reference to aip.dev

---

aep/general/0005/aep.md
aep/general/0005/aep.yaml

To help make the AEPs easier to consume, as well as provide a starting point for those who would like a from-basics starting point on API design, provide a how-to guide.

feat(AEP-5): add AEP around designing an API

---

pages/general/adopting.md
pages/general/faq.md
pages/general/licensing.md
requirements.txt

The homepage currently 404s to missing adopting and faq pages.
In addition, try to remove some Google-specific verbage.

feat: add adopting and faq

---

aep/general/0131/aep.md.j2
aep/general/0131/aep.yaml
aep/general/0131/get.proto
aep/general/0133/aep.md
aep/general/0134/aep.md
aep/general/0135/aep.md

This is a cleanup PR that also makes some small reversions to the phrasing and style of google.aip.dev/131, for the following reasons:
1) It will make it easier to adopt other AIPs as AEPs while keeping the AEPs consistent. 2) It makes this AEP more consistent with more recently-adopted AEPs. 3) I personally disagree with some of the choices made in (apparently) 2019.
I have also updated the names of some other standard method placeholders, for consistency.

Clean up AEP-131: Get.

---

aep/general/0151/aep.md.j2
aep/general/0151/aep.yaml
aep/general/0151/lro.oas.yaml
aep/general/0151/lro.proto

The changes are pretty broad, and include:
1) Refer to operations rather than status monitors.  This is based on discussion in Slack with Luke Sneeringer, who originally adopted this AEP.
2) Add references to the common components repo (aep-dev/aep) and perform corresponding cleanup in the examples.
This PR corresponds to https://github.com/aep-dev/aep/pull/8.

Clean up and modernize AIP-151: Long-running operations.

---

aep/general/0151/aep.yaml

It is not a method at all, let alone a standard one.

Move LRO to design-patterns.

---

aep/general/0132/aep.md.j2
aep/general/0132/aep.yaml

Minimal changes - just fixing broken links and making the style match other recently adopted AEPs.

Clean up AIP-132: List

---

aep/general/0210/aep.yaml

This may not be a perfect fit, but it seems closer than the design patterns category.
Maybe we rename the category to types-and-encoding?

Move AEP-UNICODE to the types category.

---

aep/general/0135/aep.md.j2

* library.longrunning.Operation -> aep.api.Operation
* name -> path

Fix some incorrect identifiers in AEP-135: Delete:

---

aep/general/0136/aep.md.j2
aep/general/0136/aep.yaml
aep/general/0136/library.proto

This is in preparation for the barn raising event, and makes the AEP more consistent with more recently-adopted AEPs.  Common guidance is also factored out of the IDL-specific tabs.
I added one new bullet point of guidance while I was at it.  I doubt this will be controversial, but calling it out for completeness.
I actually think most of the changes from the Google AIP are pretty good in this case, so I have generally not modified them.

Clean up AIP-136: Custom methods.

---

aep/general/0008/aep.md
aep/general/0008/aep.yaml

This is a fresh attempt at adding AEP-8.
The first commit is simply Google's AIP-8 copied verbatim.
The second commit contains my changes to covert to AEP.
- Mechanical changes of aip to aep
- Straightforward changes or removals of "google"
- Some small additions such as requiring OpenAPI design examples and an explanation about case conventions.

Add AEP-8 - AEP Style and Guidance

---

LICENSE.md

Since the project isn't owned by developers.google.com, we should remove the reference from the LICENSE file.

LICENSE shouldn't reference developers.google.com

---

config/site.yaml

This adds a new config option for a Google Analytics tag.
This helps address https://github.com/aep-dev/site-generator/issues/14

Add GA tag as a config option

---

aep/general/0131/aep.md.j2

hi @toumorokoshi  - here is simple PR as an example of how to ref the LRO guidance for the standard GET method. If this is ok, then go ahead an merge and I can more on another PR for the rest of the standard methods.

reference LRO guidance (address issue #106)

---

.github/PULL_REQUEST_TEMPLATE.md

Adding prettier to the checklist since formatting
is often forgotten and can result in issues with linting, impeding cycle time to merge PRs.
Describe the big picture of your changes here to communicate to the maintainers
why we should accept this pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue.
that apply_
correctly.
💝 Thank you!

chore: add prettier to checklist

---

aep/general/0127/aep.md.j2
aep/general/0127/aep.yaml

Adopt AEP 127 for https://github.com/aep-dev/aep.dev/issues/51
that apply_
correctly.
💝 Thank you!

Adop AEP 127: HTTP and gRPC Transcoding

---

aep/general/0135/aep.md.j2

* Proto tabs before OAS tabs.
* Generic HTTP guidance factored out of IDL-specific tabs.
* RPC section separated from request section.

Make the style of AEP-135: Delete consistent.

---

aep/general/130/aep.md.j2
aep/general/130/aep.yaml

Importing from https://aip.dev/130.
The main change is updating the name of AIP links to semantic names.
fixes #152.
that apply_
correctly.
💝 Thank you!

feat(methods): add AEP-130 on methods

---

aep/general/0213/aep.md.j2

This PR is based on https://github.com/aip-dev/aip.dev/pull/100, which was previously heavily reviewed (and approved by @mkistler).  The only modifications from that PR are:
* Renamed AIP to AEP everywhere / updated links.
* Updated to include Decimal.
* Some minor tweaks/improvement (such as adding **Note:** blocks indicating the protobuf-specificity of certain sections).

Adopt AIP-213: Common Components

---

aep/general/0193/aep.md.j2
aep/general/0193/aep.yaml

This PR adds AEP-193 that describes the standard structure and contents of an error response. It is significantly revised from the Google AIP-193 to adopt the HTTP standard "Problem Details" structure as defined in RFC 9547. However, I think the structure is largely compatible with the Google error response structure -- mostly differences in property names -- so I have left the proto-specific guidance from the AIP-193 in place.
I also dropped some of the details from AIP-193. In this particular AEP, I think "less is more". Let's not get bogged down in details. I think we debated details on this AEP for over a year and never got it adopted. Let's get the basics right here and leave details for later (if ever). …

Add AEP-193 Errors

---

aep/general/0124/aep.md.j2
aep/general/0124/embedded_resource.oas.yaml
aep/general/0124/embedded_resource.proto

This PR assumes that we will adopt http://aip.dev/157 without substantial changes.
Adds a new resource association pattern to aep.dev/resource-association.  This pattern supports use cases where server-side dereferencing of resource references is desirable (filtering, GraphQL-style retrieval, etc.).
that apply_
correctly.
💝 Thank you!

Define an additional pattern for resource references.

---

aep/general/0203/aep.md.j2
aep/general/0203/aep.yaml

Fixes #29 
Proto changes in https://github.com/aep-dev/aep/pull/13
It's unclear to me if we need an OpenAPI extension, but I'd guess we do?
that apply_
correctly.
💝 Thank you!

Adopt AIP-0203: Field Behavior

---

aep/general/0003/aep.md.j2
aep/general/0158/aep.md.j2
aep/general/0158/aep.yaml

AEP-158 forked from the general aip.dev, whose guidance diverged a bit from google.aip.dev.
This re-imports those, resulting in the following set of changes:
- switching typescript examples to proto (with placeholder for openapi).
- minor wording fixes.
Fixes #12 
that apply_
correctly.

feat(pagination): re-importing from AIP-158

---

aep/general/0144/aep.md.j2
aep/general/0144/aep.yaml

- lowered guidance to should (since it is not critical for an auto-generated client)
that apply_
correctly.
💝 Thank you!

feat: minor updates to arrays

---

aep/general/0157/aep.md.j2

* Add proto/OAS tabs.
* Remove Google-specific guidance.
* Add a cross-reference to a relevant section of AEP-ASSOCIATION.
that apply_
correctly.
💝 Thank you!

Clean up AEP-157: Partial responses:

---

aep/general/0159/aep.md.j2
aep/general/0159/aep.yaml

Adopt AIP-159: Reading across collections
that apply_
correctly.
💝 Thank you!

Reading across collections

---

aep/general/0159/aep.md.j2

Add guidance for supporting reading across collections with different resource hierarchies.
Note:  this is downstream of https://github.com/aep-dev/aep.dev/pull/164.
that apply_
correctly.
💝 Thank you!

Reading across collections globally

---

serve.sh

Sometimes there is a different service running at port 4000 locally, so it's not possible to use serve.sh.
Add a port field to allow it's customization.
that apply_
correctly.
💝 Thank you!

chore(serve.sh): add port feature

---

aep/general/0146/aep.md.j2
aep/general/0146/aep.yaml

Adopt Google's AIP-146: Generic fields.
Note that I didn't use tabs to separate protobuf from OAS content because the site generator breaks with headers inside a tab, and there's too much (useful) proto guidance to organize without headers.
that apply_
correctly.

Generic fields

---

aep/general/0122/aep.md.j2
aep/general/0151/aep.md.j2
aep/general/0155/aep.md.j2

These links were not rendering properly.

Fix links with backticks.

---

MAINTAINERS.md
aep/general/0001/aep.md.j2

The technical steering committe is outdated. Link it to the more visible and current MAINTAINERS.md.
that apply_
correctly.

fix(purpose): link to maintainers instead of hardcode

---

aep/general/0134/aep.md.j2

In protobuf, the resource path is only an input parameter in the context of update. This has resulted in increased complexity, such as the introduction of an `IDENTIFIER` field behavior that must be special-cased by linters and generators.
Normalizing update to the same pattern fixes this issue.
related to #181
that apply_
correctly.

feat(update): introduce "path" variable

---

aep/general/0004/aep.md.j2
aep/general/0131/aep.md.j2
aep/general/0131/get.oas.yaml
aep/general/0141/aep.md.j2

This changes our OAS guidance to ensure that the GET method returns only a schema that is annoted with `x-aep-resource`. It also changes our guidance on resource types to show that there's an expectation that all resources have a corresponding OAS component with `x-aep-resource`
that apply_
correctly.
💝 Thank you!

Add component mandate for OAS resources

---

aep/general/0134/aep.md.j2
aep/general/0159/aep.md.j2
aep/general/0193/aep.md.j2

These are a couple of quick fixes that were breaking the new site generator.
that apply_
correctly.
💝 Thank you!

Issues found during site-generator building

---

aep/general/0005/aep.md.j2
aep/general/0008/aep.md.j2
aep/general/0009/aep.md.j2
aep/general/0122/aep.md.j2
aep/general/0131/aep.md.j2
aep/general/0133/aep.md.j2
aep/general/0134/aep.md.j2
aep/general/0135/aep.md.j2
aep/general/0144/aep.md.j2
aep/general/0151/aep.md.j2
aep/general/0164/aep.md.j2
aep/general/130/aep.md.j2

I noticed a few dead links so decided to fix them.
Specifically:
- Replaced links to AIPs with links to the relevant AEP
- Fixed a few badly formatted links
- Migrated links from AEP-123 and AIP-123 to AEP-4. AIP-123 was [imported to AEP-4](https://github.com/aep-dev/aep.dev/pull/76/files) and the links were not all updated.
- Migrated links from AEP-9 and AIP-9 to AEP-3. AIP-9 was imported as AEP-3 and the links were not all updated.
- Removed the folder for AEP-9 as it is now just an empty shell.
- Fixed any broken links I noticed while doing the above work. I didn't comprehensively check the entire repository.
that apply_ …

Fix deadlinks

---

.github/workflows/publish_site.yaml

This adds a new Github Actions workflow that triggers the site-generator-beta to publish whenever a new commit is made to main. site-generator-beta is responsible for cloning from main + publishing the new site.
A new organization secret will be required. I have the token but I need permission to add it to the org (preferably) or the repo
that apply_
correctly.
💝 Thank you!

Add publish script for new website

---

aep/general/0162/aep.md.j2
aep/general/0162/aep.yaml

Adapted from aip.dev/162.
list of changes include:
- changing references to "name" to "path".
- minor formatting changes like consolidating proto examples so we can minimize the proto/openapi tabs.
- removed some sections from rationale that spoke to aip.dev more than aeps, and didn't provide valuable context (like the existence of "tag" in older versions of the pattern).
- added openapi schemas.
fixes #16.
that apply_
correctly.
[Document …

feat(revisions): adopt aep-162 revisions

---

aep/general/0004/aep.md.j2

There's clauses around protobuf / kubernetes / openapi that are not relevant - this is already illustrated in the examples.
that apply_
correctly.

fix(resource-types): remove uneeded resource type naming guidance

---

aep/general/0231/aep.md.j2
aep/general/0231/aep.yaml
aep/general/0231/batchget.oas.yaml

Adopt AEP 231 - Batch Get
that apply_
correctly.
💝 Thank you!

Adopt AEP 231 - Batch Get

---

aep/general/0124/aep.md.j2
aep/general/0126/aep.md.j2
aep/general/0132/aep.md.j2
aep/general/0135/aep.md.j2
aep/general/0136/aep.md.j2
aep/general/0144/aep.md.j2
aep/general/0151/aep.md.j2
aep/general/0164/aep.md.j2
aep/general/0231/aep.md.j2

Change all of the YAML samples to use the new JSONPath (ish) syntax
that apply_
correctly.
💝 Thank you!

Jsonpath changes

---

aep/general/0121/aep.md.j2
aep/general/0133/aep.md.j2
aep/general/0134/aep.md.j2
aep/general/0135/aep.md.j2
aep/general/0154/aep.md.j2

The introduction of the concept of management plane and data plane and it's subjective definition in the AEPs was leading to ambiguous guidance. Removing the mention of those concepts until a clearer criteria can be established.
This change requires that a decision must be made for strong consistency. As operations that are not strongly consistent can result in manual per-resource patches for declarative clients, require strong consistency for all standard methods.
that apply_
correctly.

fix(methods): remove management plane, require strong consistency

---

aep/general/0133/aep.md.j2
aep/general/0134/aep.md.j2
aep/general/0158/aep.md.j2
aep/general/0217/aep.md.j2
aep/general/oas.yaml

Adding oas examples for create.
This also tests out the pattern outlined in #230 -  adding a generated oas.yaml and use selective elements from it as an example, which looks to work pretty well.
There is a blocker on https://github.com/aep-dev/site-generator-beta/issues/43 to allow for support from a json-path like structure to target sub-elements, but this will at least allow for selective guidance to be easily added.
This PR also does some smaller changes to flesh out or normalize the oas guidance, including removing
the example LRO in exchange for just referencing it instead.
that apply_
[references …

fix(133): add oas examples

---

aep/general/0136/aep.md.j2

The existing guidance was a big vague on the impact of a custom method in a declarative client. This 
attempts to clarify the impact of making that choice.
that apply_
correctly.
💝 Thank you!

feat(136): improve wording around declarative clients

---

aep/general/0008/aep.md.j2

Since error codes can be succinct when describing gRPC and HTTP+JSON, we can just name them both in the AEPs.
that apply_
correctly.
💝 Thank you!

feat(8): adding style guide on error codes

---

aep/general/0134/aep.md.j2
aep/general/0137/aep.md.j2
aep/general/0137/aep.yaml
aep/general/example.oas.yaml
aep/general/example.proto

add a new standard method to document apply / PUT.
This AEP is useful for:
- APIs that would like to offer a PUT endpoint, but has lacked guidance from the AEPs.
- APIs that would like to expose a declarative-friendly API  endpoint (the integration of which is simpler than apply).
Apply can also serve as an alternative to expose a create and update endpoint.
This PR also performs a few quick fixes:
- referencing the example proto instead of hard-coding the example.
- some minor fixes on the openapi (removing empty schema)
- minor fixes on the proto (removing invalid fields like 'id')
that apply_ …

feat(137): add apply AEP

---

aep/general/0134/aep.md.j2

create or update introduces a new pattern in addition to the existing flow of:
1. getting a resource.
2. if NOT_FOUND, send a create.
3. if found, send an update.
In the future, this could be re-added as an Apply method, which would map to the appropriate REST method of PUT.
that apply_
correctly.
💝 Thank you!

feat(update): remove create or update

---

aep/general/0134/aep.md.j2
aep/general/example.oas.yaml

After offline discussion, it was agreed upon that IETF RFC 7396 (JSON Merge Patch) is the more sensible choice for a partial update on an HTTP+JSON API. The rationale includes:
- can generally be expressed via protobuf field masks.
- aligns with the AEPs usage of resource-oriented guidance.
- aligns with an existing IETF standard, which as already been widely adopted.
Other minor changes:
- removes duplicative guidance around LROs to make the AEP succinct.
- populates oas guidance, sans etags which may require some more design (in HTTP etags are not added to the resource body).
Fixes #109.
that apply_ …

fix(update): add json-merge-patch guidance

---

aep/general/0131/aep.md.j2

Just adding a link to the x-aep-resource extension.
that apply_
correctly.
💝 Thank you!

Add a link to the x-aep-resource extension in aep-131

---

aep/general/0132/aep.md.j2
aep/general/0133/aep.md.j2

There is currently some inconsistency with the description of parent fields on standard methods, and whether they are required.
Clarifying that they are indeed optional, as the resource may not have a parent.
that apply_
correctly.
💝 Thank you!

fix(standard-methods): clarify optional parent fields

---

aep/general/0135/aep.md.j2
aep/general/0136/aep.md.j2
aep/general/example.oas.yaml

The existing OpenAPI example did not adhere to 
the openapi-linter.
Some minor fixes on using the common example 
OAS proto.
that apply_
correctly.
💝 Thank you!

fix(openapi): publishes oas that passes linter

---

.github/PULL_REQUEST_TEMPLATE.md

Often, we are making spot fixes to AEPs, and not introducing brand new ones. Therefore, the PR template should comment out new AEP guides rather than requiring it to be removed.
that apply_
correctly.
💝 Thank you!

chore: PR template comments out new AEP checklist

---

aep/general/0130/aep.md.j2

To help with more standard generation of clients,
propose a standard for OAS operation IDs.
fixes #208
that apply_
correctly.
💝 Thank you!

feat(130): add guidance around OAS OperationIDs

---

config/hero.yaml
pages/general/adopting.md
pages/general/faq.md

will update links after #231 is addressed
that apply_

Stubbing out the aep tooling list

---

config/hero.yaml
pages/general/tooling-and-ecosystem.md

Add a section that discusses the AEP tooling ecosystem. This will better improve the discoverability of the tools.
The site-generator does not currently support mermaid, but I think it'd be great if it did and we merge this in rather that switch to graphviz, which is missing highlighting of links.
Example render in my editor:
that apply_
correctly.
💝 Thank you!

docs: add tooling section

---

aep/general/example.oas.yaml

fix incorrect examples:
- incorrect content type for update.
- id field for create was missing.
fixes #271
that apply_
correctly.
💝 Thank you!

fix(example): content-type for update, id field for create

---

aep/general/0154/aep.md.j2

RFC 9110 obsoletes RFC 7232 and clarifies some details.
In addition, clarifying expectation of behavior on preconditions  which are not supported. They should be rejected to help indicate the lack of support to the user.
Fixes #254.
that apply_
correctly.
💝 Thank you!

feat(AEP-154): update to conform to RFC 9110, clarify precondition error code

---

aep/general/0132/aep.md.j2

It's unclear at this point what order the various AEPs should be applied on an API endpoint, if they exist.
Adding a section to clarify this. An example of this precedence is drafted at https://github.com/aep-dev/aepc/pull/60.
that apply_
correctly.
💝 Thank you!

feat(132): clarify operator precedence

---

blog/2025-roadmap.md
scripts/build.sh

that apply_
correctly.
💝 Thank you!

2025 roadmap blog post

---

aep/general/0003/aep.md.j2
aep/general/0004/aep.md.j2
aep/general/0005/aep.md.j2
aep/general/0008/aep.md.j2
aep/general/0121/aep.md.j2
aep/general/0124/aep.md.j2
aep/general/0127/aep.md.j2
aep/general/0130/aep.md.j2
aep/general/0132/aep.md.j2
aep/general/0133/aep.md.j2
aep/general/0134/aep.md.j2
aep/general/0135/aep.md.j2
aep/general/0137/aep.md.j2
aep/general/0144/aep.md.j2
aep/general/0148/aep.md.j2
aep/general/0151/aep.md.j2
aep/general/0154/aep.md.j2
aep/general/0156/aep.md.j2
aep/general/0158/aep.md.j2
aep/general/0162/aep.md.j2
aep/general/0191/aep.md.j2
aep/general/0192/aep.md.j2
aep/general/0205/aep.md.j2
aep/general/0211/aep.md.j2
aep/general/0214/aep.md.j2
aep/general/0216/aep.md.j2

Some people are using a new version of prettier.
Using an old one can increase friction
for new contributors.
that apply_
correctly.
💝 Thank you!

chore: upgrade prettier to 3.5.1

---

aep/general/0003/aep.md.j2
aep/general/0121/aep.md.j2

We are missing a term to describe a resource whose collection has no parents. Since this is helpful for things like building a navigation tree, define the term.
that apply_
correctly.
💝 Thank you!

feat(3): add terminology for root resources and collections

---

aep/general/0008/aep.md.j2
aep/general/0101/aep.md.j2
aep/general/0101/aep.yaml

Add a new AEP that can clarify guidance around the usage of OpenAPI and OAS. The primary motivation is  to document the OAS version that should be used,
but this will be helpful to clarify additional 
guidance as needed.
Fixes #213 
that apply_
correctly.
💝 Thank you!

feat(101): add OpenAPI AEP

---

aep/general/0001/aep.md.j2

I'd like to remove the Graphviz dependency from our site generator, so we're only using one diagramming tool. 
This is what the final diagram will look like (ignore the dotted background, I'm taking this from an online visualization tool):
that apply_
correctly.
💝 Thank you!

Replace Graphviz diagram with Mermaid

---

aep/general/0004/aep.md.j2
aep/general/0156/aep.md.j2

Now that a formal x-aep-resource extension was added, adding
references to said extension. 
In addition, the `singleton` field was added. Adding appropriate
guidance.
that apply_
correctly.
💝 Thank you!

feat(156): add x-aep-resource and singleton annotation

---

.github/workflows/lint.yaml
aep/general/example.oas.yaml

The json-like syntax of the example OAS yaml was making it seem like the content coudl be treated like json, when it could not.
Using the standard yaml indented syntax clarifies this.
fixes #303
that apply_
correctly.
💝 Thank you!

fix(example, oas): switch to yaml tab syntax

---

aep/general/0122/aep.md.j2
aep/general/0132/aep.md.j2

Some guidance includes "should" on parent fields. However, this is a requirement in order for AEP clients and users to understand the resource hierarchy.
This is an artifact of the adaptation of the AEP from aip.dev, and currently there is not justification for the *should*.
Addresses #314 
that apply_
correctly.
💝 Thank you!

fix(132): should -> must on parent field

---

aep/general/0145/aep.md.j2

Closes #310 
This replaces the Typescript syntax with Proto / OpenAPI.

Change AEP-145 examples to Proto / OpenAPI

---

aep/general/0134/aep.md.j2

Previously, there was bespoke guidance in the Update AEP that refered to using a custom ETag field in the resource for validating previous resource state.
This guidance somewhat duplicates the guidance in RFC 9110  and AEP-154 which states that it should be adhered to. This  duplication can lead to partial support of both, which in turn will make client integration more difficult.
Therefore, removing this guidance. Fixes #241
that apply_
correctly.
💝 Thank you!

feat(134): replace etag guidance with 154 reference

---

aep/general/0003/aep.md.j2
aep/general/0004/aep.md.j2
aep/general/0102/aep.md.j2
aep/general/0102/aep.yaml

Adding an AEP around APIs specifically, to include more specific guidance and a landing page for APIs.
Clarifying some guidance around the usage of sub-paths for API names: previously this was confusing as an example existed (`api.example.com/users`) which seemed to allow this, but the API name guidance did not allow path elements in the API  name.
Also adding guidance for the `type` field in the `x-aep-resource` oas annotation: this was missing from the schema annotation previously, which effectively did not require placing the  api name anywhere in an OAS schema description.
that apply_
[references …

feat(102): add new AEP around APIs

---

aep/general/0154/aep.md.j2
aep/general/0154/aep.yaml

There was ambiguity around what to do if preconditions are not  supported by an API. This guidance already existed in some  form in the AEP, but raising it up front and center to help clarify universally what the behavior should be.
In addition, renaming the aep from `/etags` and "resource freshness validation" to "preconditions", to match the IETF RFC.
that apply_
correctly.
💝 Thank you!

feat(154): clarify behavior if not supported

---

aep/general/0137/aep.md.j2

Filling some gaps in the guidance to clarify what to do if  fields are not present. As well as if fields are not  present.
Fixes #123.
that apply_
correctly.
💝 Thank you!

fix(137): clarify behavior (field presence and errors).

---

aep/general/0122/aep.md.j2
aep/general/0124/aep.md.j2

The previous guidance was ambiguous about when to use a full resource name vs a relative one. 
This ambiguity makes it difficult for clients to read the location of  the remote resource, as well as the ablity to resolve it as necessary.
Some forms of REST APIs already put the full resource name directly in the  payload, so there is precedence for this approach.
Clarifying the guidance to ensure consistent behavior for APIs.
fixes #264 
that apply_
correctly.
💝 Thank you!

fix(122): always use full resource path for API references
