aep-dev/aeps

MAINTAINERS.md
* added myself
* reordered list to be alphabetical by first name
* changed filename from `OWNERS.md` > `MAINTAINERS.md` in order to better agree with the existing charter. (We may choose to re-add a new OWNERS file if that seems to be useful.)
=> Update and rename OWNERS.md to MAINTAINERS.md

aep/general/0002/aep.md, aep/general/0002/aep.yaml, aep/general/0151/lro.oas.yaml, requirements.txt
Adding an AEP about numbering enables
a clear organization for future contributions.
Modification of existing AEPs to the new numbering scheme will
be added in future commits.
=> feat(AIP-2): add AEP around numbering.

aep/general/0121/aep.md, aep/general/0121/aep.yaml
- slight rewording on a few sections.
- removal of the wording "stateless protocol", which was generally confusing and debated at Google.
=> feat(121): porting AEP-121 from AIP-121

CONTRIBUTING.md
adding an example of how to run prettier to reduce contributing friction.
=> chore(contributing): add prettier command

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a pullrequest template to the repository. It resolves #91.
What types of changes does your code introduce to AEP?
_Put an `x` in the boxes that apply_
Please review the [AEP Style and Guidance](https://aep.dev/style-guide) for contributing to this repository.
=> feat: Add GitHub pullrequest template

aep/general/0216/aep.md.j2, aep/general/0216/aep.yaml
Other than the superficial changes, this PR:
* Changes some instances of **should** to **must**.
* Removes some guidance that is redundant with the general custom method guidance.
that apply_
correctly.
💝 Thank you!
=> Adopt AIP-216: States from google.aip.dev.

aep/general/0211/aep.md.j2
A couple cleanups on wording (to go for a more formal tone), as well as moving *should* to *must*.
Fixes #18.
that apply_
correctly.
=> feat(authorization): upgrade some shoulds to must.

aep/general/0160/aep.md.j2, aep/general/0160/aep.yaml
that apply_
correctly.
💝 Thank you!
=> Adopt AEP-160: Filtering

aep/general/0191/aep.md.j2, aep/general/0191/aep.yaml
that apply_
correctly.
💝 Thank you!
=> AEP-0191: File and Directory Structure

aep/general/0192/aep.md.j2, aep/general/0192/aep.yaml
=> AEP-192: Documentation

aep/general/0217/aep.md.j2, aep/general/0217/aep.yaml
Adopt AIP-217: Unreachable resources
that apply_
correctly.
=> Unreachable resources

aep/general/0140/aep.md.j2, aep/general/0140/aep.yaml
Adopt AIP-140: Field names
that apply_
correctly.
=> Field names

aep/general/0157/aep.md.j2
Address a comment from https://github.com/aep-dev/aep.dev/pull/197.
I accidentally allowed the PR to auto-merge before pushing this commit.
=> Partial response cleanup cleanup

CONTRIBUTING.md
aep.dev is not officially affiliated with Google.
that apply_
correctly.
=> fix(contributors): remove Google CLA

aep/general/0144/aep.md.j2, scripts/build.sh
Forgot to change one last file.
that apply_
correctly.
💝 Thank you!
=> One more JSONPath change + addition to build script

.github/workflows/publish_site.yaml, scripts/build.sh
Change pipelines to reference new repo names.
that apply_
correctly.
💝 Thank you!
=> Change pipelines

aep/general/0144/aep.md.j2
This path is invalid, so it breaks the generator with the new fix.
that apply_
correctly.
💝 Thank you!
=> fix sample path

aep/general/0005/aep.md.j2
some links are not supported by the new site-generator, and should be corrected regardless.
that apply_
correctly.
=> fix(5): fix broken links

aep/general/0133/aep.md.j2, aep/general/0133/aep.yaml, aep/general/0134/aep.yaml, aep/general/0135/aep.yaml
some minor updates, mostly with using the proto/
openapi shared example instead of hand-written ones.
that apply_
correctly.
=> fix: minor updates

config/hero.yaml
that apply_
correctly.
💝 Thank you!
=> docs: fix broken tooling-and-ecosystem link

blog/2024-in-review.md
This commits our first blog post to the aeps directory. The site-generator doesn't currently take in the blog posts, but this PR is a prerequisite. 
that apply_
correctly.
💝 Thank you!
=> commit blog post to aeps directory

blog/history-of-aeps.md
that apply_
correctly.
💝 Thank you!
=> blog: add post on history of AEPs

.github/workflows/lint.yaml, .gitignore, CONTRIBUTING.md, package-lock.json, package.json
using package.json will ensure that prettier
versions are consistent.
that apply_
correctly.
💝 Thank you!
=> chore: use package.json to lock prettier version

aep/general/example.oas.yaml
example should have next_page_token, as outlined in AEP-158.
fixes #282 
that apply_
correctly.
💝 Thank you!
=> fix(132): add next_page_token to example

aep/general/0132/aep.md.j2
The previous examples for the response were pointing to  the request.
that apply_
correctly.
💝 Thank you!
=> fix(132): fix response examples

aep/general/0151/aep.md.j2
With json-schema now mounted on aep.dev, we can provide better references.
that apply_
correctly.
💝 Thank you!
=> fix(151): update json-schema url for operation

blog/terraform-post.md
Remove duplicate author and names.
that apply_
correctly.
💝 Thank you!
=> remove title and authors duplicate

aep/general/0155/aep.yaml, aep/general/scope.yaml
Looks like AEP-155 isn't in the sidebar currently. That's because it was in a separate category called 'requests' and we don't have that listed in our category list.
As opposed to creating a new category with one AEP, I think we should move this over to Design Patterns. Happy to be overruled!
that apply_
correctly.
💝 Thank you!
=> Move AEP-155 to Design Patterns.

pages/general/tooling-and-ecosystem.md
A few more tools were added in the past couple of months, adding them to the tooling diagram.
that apply_
correctly.
💝 Thank you!
=> chore(tooling): update tooling diagram

aep/general/0127/aep.md.j2, aep/general/0132/aep.md.j2, aep/general/0136/aep.md.j2, aep/general/0145/aep.md.j2, aep/general/0193/aep.md.j2, aep/general/example.oas.yaml, aep/general/example.proto
follow up to #309, this completes outstanding work to make snake_case the standard way to describe fields.
There was a bug with migrating the proto (the site generator is unable to resolve some symbols like ArchivePublisher). That  will be followed up in a separate PR.
that apply_
correctly.
💝 Thank you!
=> fix(140): camelCase -> snake_case examples

aep/general/0181/aep.md.j2, aep/general/0181/aep.yaml
aip.dev/181 discusses stability levels of the APIs themselves.
There have been discusses on and off about adopting this AIP, but there has not yet been consensus on whether it is valuable to adopt: it effectively provides a restriction on versioning of the APIs that is not materially related to the clients.
In addition, some AEP maintainers are considering a separate proposal that introduces date-based versioning schemes for APIs to handle introducition and removal of fields. Since that may supercede this proposal in the future, that is another reason to not keep a placeholder  value for an aip that may ultimately have separate guidance.
that apply_
Please review the [AEP Style and …
=> feat(181): remove placeholder

aep/general/0001/aep.md.j2, aep/general/0127/aep.md.j2, aep/general/0131/aep.md.j2, aep/general/0132/aep.md.j2, aep/general/0133/aep.md.j2, aep/general/0134/aep.md.j2, aep/general/0136/aep.md.j2, aep/general/0164/aep.md.j2, aep/general/0193/aep.md.j2
that apply_
correctly.
💝 Thank you!
=> chore: add links between AEPs

aep/general/0127/aep.md.j2
Fixes #330
that apply_
correctly.
💝 Thank you!
=> fix(127): recommend using json_name annotation for consistency with AEP-140

aep/general/0154/aep.md.j2
Some links were dead on AEP-154.
that apply_
correctly.
💝 Thank you!
=> chore(154): cleanup links

aep/general/0151/aep.md.j2
fixing a few missing pieces in the LRO AEP
Removing the custom guidance on LROs specifically to 202 to just return whatever the standard response is of the method originally.
Fixing broken links.
Updating documentation to use the standard style of  documenting status codes (GRPC / HTTP)
fixes #224
that apply_
correctly.
💝 Thank you!
=> fix(151): add missing status
